//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offers
    {
        public int ID { get; set; }
        public Nullable<int> ID_SubOffers { get; set; }
        public Nullable<int> ID_Broker { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> ID_Client { get; set; }
    
        public virtual Broker Broker { get; set; }
        public virtual Sub_Offers Sub_Offers { get; set; }
        public virtual Deal Deal { get; set; }
    }
}
